source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '10.0'
target 'AdvanceSDK_Example' do

  #必须集成
  pod 'AdvanceSDK', :path => '../'
  
  #集成倍业所需
  pod 'AdvanceSDK/Mercury', :path => '../'
  pod 'MercurySDK', '3.1.8.9'

  #集成穿山甲所需
  pod 'AdvanceSDK/CSJ', :path => '../'
  pod 'Ads-CN', '4.9.0.6'
  
  #集成广点通所需
  pod 'AdvanceSDK/GDT', :path => '../'
  pod 'GDTMobSDK', '4.14.10'

  #集成快手所需
  pod 'AdvanceSDK/KS', :path => '../'
  pod 'KSAdSDK', '3.3.40'

  # 集成百度 所需
  pod 'AdvanceSDK/BD', :path => '../'
  pod 'BaiduMobAdSDK', '5.101'

  # 集成GroMoreBidding 所需
  pod 'AdvanceSDK/GroMoreBidding', :path => '../'

  
  
  pod 'SDWebImage', '5.12.1'
  pod 'Masonry'

  target 'AdvanceSDK_Tests' do
    inherit! :search_paths
    
  end
  
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    end
  end

end
