source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '12.0'
target 'AdvanceSDK_Example' do

  #必须集成
  pod 'AdvanceSDK', :path => '../'
  
  #集成倍业Adapter
  pod 'AdvanceSDK/MercuryAdapter', :path => '../'
  pod 'MercurySDK', '4.4.6'

  #集成穿山甲Adapter
  pod 'AdvanceSDK/CSJAdapter',  :path => '../'
  pod 'Ads-CN-Beta', '6.6.0.7', :subspecs => ['BUAdSDK', 'CSJMediation']

  #集成广点通Adapter
  pod 'AdvanceSDK/GDTAdapter', :path => '../'
  pod 'GDTMobSDK', '4.15.10'

  #集成快手Adapter
  pod 'AdvanceSDK/KSAdapter', :path => '../'
  pod 'KSAdSDK', '3.3.72'

  #集成百度Adapter
  pod 'AdvanceSDK/BDAdapter', :path => '../'
  pod 'BaiduMobAdSDK', '5.371'
  
  #集成TanxAdapter
  pod 'AdvanceSDK/TanxAdapter', :path => '../'
  pod 'TanxSDK', '3.6.6'
  

  #Third
  pod 'SDWebImage'
  
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
        end
      end
    end
  end

end
