use_frameworks!

platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'AdvanceSDK_Example' do

  pod 'AdvanceSDK', :path => '../'
  pod 'AdvanceSDK/Mercury', :path => '../'
  pod 'AdvanceSDK/CSJ', :path => '../'
  pod 'AdvanceSDK/GDT', :path => '../'
  pod 'AdvanceSDK/KS', :path => '../'
  pod 'AdvanceSDK/BD', :path => '../'
  pod 'AdvanceSDK/Bidding', :path => '../'

  pod 'JSONModel', '1.8.0'
  pod 'Reachability', '3.2'
  pod 'SDWebImage', '5.12.1'

  pod 'Masonry'
#  pod 'Ads-CN', '4.4.0.0'

#  pod "STDebugConsole"
#  pod 'JPFPSStatus'

  target 'AdvanceSDK_Tests' do
    inherit! :search_paths
    
  end
end
